//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stellaris_Lobby_Manager {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stellaris_Lobby_Manager.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Barred Spiral 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_bar {
            get {
                return ResourceManager.GetString("galaxyShape.en.bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cartwhell 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_cartwheel {
            get {
                return ResourceManager.GetString("galaxyShape.en.cartwheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elliptical 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_elliptical {
            get {
                return ResourceManager.GetString("galaxyShape.en.elliptical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ring 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_ring {
            get {
                return ResourceManager.GetString("galaxyShape.en.ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spiral (2 Arms) 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_spiral_2 {
            get {
                return ResourceManager.GetString("galaxyShape.en.spiral_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spiral (3 Arms) 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_spiral_3 {
            get {
                return ResourceManager.GetString("galaxyShape.en.spiral_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spiral (4 Arms) 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_spiral_4 {
            get {
                return ResourceManager.GetString("galaxyShape.en.spiral_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spiral (6 Arms) 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_spiral_6 {
            get {
                return ResourceManager.GetString("galaxyShape.en.spiral_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spoked 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_spoked {
            get {
                return ResourceManager.GetString("galaxyShape.en.spoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starburst 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_en_starburst {
            get {
                return ResourceManager.GetString("galaxyShape.en.starburst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 棒旋型 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_bar {
            get {
                return ResourceManager.GetString("galaxyShape.zh.bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车轮型 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_cartwheel {
            get {
                return ResourceManager.GetString("galaxyShape.zh.cartwheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 椭圆型 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_elliptical {
            get {
                return ResourceManager.GetString("galaxyShape.zh.elliptical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆环型 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_ring {
            get {
                return ResourceManager.GetString("galaxyShape.zh.ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋涡型（双旋臂） 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_spiral_2 {
            get {
                return ResourceManager.GetString("galaxyShape.zh.spiral_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋涡型（三旋臂） 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_spiral_3 {
            get {
                return ResourceManager.GetString("galaxyShape.zh.spiral_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋涡型（四旋臂） 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_spiral_4 {
            get {
                return ResourceManager.GetString("galaxyShape.zh.spiral_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋涡型（六旋臂） 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_spiral_6 {
            get {
                return ResourceManager.GetString("galaxyShape.zh.spiral_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辐条型 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_spoked {
            get {
                return ResourceManager.GetString("galaxyShape.zh.spoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星暴型 的本地化字符串。
        /// </summary>
        internal static string galaxyShape_zh_starburst {
            get {
                return ResourceManager.GetString("galaxyShape.zh.starburst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Huge (1000 Stars) 的本地化字符串。
        /// </summary>
        internal static string galaxySize_en_huge {
            get {
                return ResourceManager.GetString("galaxySize.en.huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large (800 Stars) 的本地化字符串。
        /// </summary>
        internal static string galaxySize_en_large {
            get {
                return ResourceManager.GetString("galaxySize.en.large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium (600 Stars) 的本地化字符串。
        /// </summary>
        internal static string galaxySize_en_medium {
            get {
                return ResourceManager.GetString("galaxySize.en.medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small (400 Stars) 的本地化字符串。
        /// </summary>
        internal static string galaxySize_en_small {
            get {
                return ResourceManager.GetString("galaxySize.en.small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tiny (200 Stars) 的本地化字符串。
        /// </summary>
        internal static string galaxySize_en_tiny {
            get {
                return ResourceManager.GetString("galaxySize.en.tiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巨型（1000 恒星） 的本地化字符串。
        /// </summary>
        internal static string galaxySize_zh_huge {
            get {
                return ResourceManager.GetString("galaxySize.zh.huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大型（800 恒星） 的本地化字符串。
        /// </summary>
        internal static string galaxySize_zh_large {
            get {
                return ResourceManager.GetString("galaxySize.zh.large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中型（600 恒星） 的本地化字符串。
        /// </summary>
        internal static string galaxySize_zh_medium {
            get {
                return ResourceManager.GetString("galaxySize.zh.medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小型（400 恒星） 的本地化字符串。
        /// </summary>
        internal static string galaxySize_zh_small {
            get {
                return ResourceManager.GetString("galaxySize.zh.small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 袖珍（200 恒星） 的本地化字符串。
        /// </summary>
        internal static string galaxySize_zh_tiny {
            get {
                return ResourceManager.GetString("galaxySize.zh.tiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config error ❌ 的本地化字符串。
        /// </summary>
        internal static string info_en_configError {
            get {
                return ResourceManager.GetString("info.en.configError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Galaxy list fetch error ❌ 的本地化字符串。
        /// </summary>
        internal static string info_en_galaxyError {
            get {
                return ResourceManager.GetString("info.en.galaxyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stellaris.exe Not Found ❌ 的本地化字符串。
        /// </summary>
        internal static string info_en_gameNotFound {
            get {
                return ResourceManager.GetString("info.en.gameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game lobby not found ❌ 的本地化字符串。
        /// </summary>
        internal static string info_en_lobbyNotFound {
            get {
                return ResourceManager.GetString("info.en.lobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ✔️ 的本地化字符串。
        /// </summary>
        internal static string info_en_noError {
            get {
                return ResourceManager.GetString("info.en.noError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置错误 ❌ 的本地化字符串。
        /// </summary>
        internal static string info_zh_configError {
            get {
                return ResourceManager.GetString("info.zh.configError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星系设定列表获取错误 ❌ 的本地化字符串。
        /// </summary>
        internal static string info_zh_galaxyError {
            get {
                return ResourceManager.GetString("info.zh.galaxyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未发现 Stellaris.exe ❌ 的本地化字符串。
        /// </summary>
        internal static string info_zh_gameNotFound {
            get {
                return ResourceManager.GetString("info.zh.gameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏大厅未找到 ❌ 的本地化字符串。
        /// </summary>
        internal static string info_zh_lobbyNotFound {
            get {
                return ResourceManager.GetString("info.zh.lobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ✔️ 的本地化字符串。
        /// </summary>
        internal static string info_zh_noError {
            get {
                return ResourceManager.GetString("info.zh.noError", resourceCulture);
            }
        }
    }
}
